wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1651393556
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 3
      - 13
      - 16
      4: 3.8.0
      5: 0.12.11
      8:
      - 5
cost_limit:
  desc: null
  value: 0
cpu:
  desc: null
  value: 4
env:
  desc: null
  value: intersectionhard-v0
gamma:
  desc: null
  value: 0.99
hid:
  desc: null
  value: 256
l:
  desc: null
  value: 2
max_ep_len:
  desc: null
  value: 4000
num_steps:
  desc: null
  value: 500000.0
proj_name:
  desc: null
  value: Intersection
run_name:
  desc: null
  value: ppo_hard
safe_check:
  desc: null
  value: false
seed:
  desc: null
  value: 0
steps_per_epoch:
  desc: null
  value: 4000
